name: automerge
on:
  schedule:
    - cron: '0 13 * * 3' # utc 기준 시간
    # Asia/Seoul 기준 수요일 22시에 실행
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.MERGE_TOKEN }}"
          MERGE_LABELS: ""